#!/bin/sh

ENABLED=no
PROCS=ss-server
ARGS="-c /opt/etc/ss_server.json -u"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /etc_ro/init.d/rc.func
